### ISSUE TITLE
Implement Indexing for Performance

### ISSUE THREAD

**Issue by sofushn** [RUC-MSc-CS-CIT-2024/portfolio_subproject_1#20]
We should add indexes to tables and queries to improve search and retrieval performance.

E.1. Consider the extensions developed under D and discuss/explain what may potentially
provide significant performance improvements. Describe how your database is indexed
(observe: this concerns database indexing, not textual inverted indexing – even though the
latter may build on the former).

## Todo

Go through all tables and columns and list the columns that would make sense to index (list the columns as a comment for this issue)

**Comment by JuliusKryger** [comment]
### My recommendations in where we should be Indexing

1. **Foreign Key Columns**

    - **user_id** in the following tables:
        - `search_history`
        - `bookmark`
        - `completed`
        - `user_score`

      **Reason**: We will be doing quite a few joins using these columns. Indexing them will optimize queries retrieving user-specific data like (bookmarks, completed media, scores, or search history).

    - **media_id** in multiple tables:
        - `bookmark`, `completed`, `user_score`, `season`, `episode`, `media_genre`, `media_production_country`, `score`, `media_in_collection`, `related_media (primary_id, related_id)`, `release`, `crew_member`, `cast_member`, `media_production_company`

      **Reason**: Indexing `media_id` across these tables speeds up queries related to media entities (bookmarks, scores, genres, production companies).

    - **person_id** in the following tables:
        - `crew_member`, `cast_member`

      **Reason**: Indexing `person_id` will optimize queries for media involving specific cast and crew members.

2. **Commonly Queried Columns**

    - **username** and **email** in `user` table:
      **Reason**: These fields are frequently used in user lookups like (login, registration). Indexing these will improve our query performance.

    - **completed_date** in `completed` table:
      **Reason**: Indexing will improve queries that sort or filter by completed date.

    - **score_value** in `user_score` table:
      **Reason**: I imagine this would frequently be used for filtering or sorting by user scores.

    - **type** in `search_history` and `media` tables:
      **Reason**: Filtering by type (movie vs series) benefits from indexing.

    - **collection_id** in `media_in_collection` table:
      **Reason**: Indexing will speed up queries determining which media belong to a specific collection.

3. **Composite Indexes**

    - **(media_id, country_id)** in `media_production_country` table:
      **Reason**: Indexing these together will optimize queries filtering by both media and country.

    - **(collection_id, media_id)** in `media_in_collection` table:
      **Reason**: This composite primary key would give us faster lookups.

**Comment by JuliusKryger** [comment]
Should this task be handled by editing one of our existing scripts, such as the create scripts used for setting up the database or the population scripts for inserting data? 

Adding the indexing there would ensure it is applied during database creation or data population. Alternatively, should we create a separate script specifically for managing indexes and constraints?

Which solution do you guys prefer?

**Comment by sofushn** [comment]
> Should this task be handled by editing one of our existing scripts, such as the create scripts used for setting up the database or the population scripts for inserting data?

It should 👍
