### ISSUE TITLE
Move title to its own table

### ISSUE THREAD

**Issue by sofushn** [RUC-MSc-CS-CIT-2024/portfolio_subproject_1#50]
Title is not part of a release and should be move to its own table, including the title type, title language, title region

Also includes adding attributes to the title

**Comment by JuliusKryger** [comment]
This issue is closed right?
This is the commit that should have closed this issue right?
be50148e55dc71d921da239bd6a77ede1857946a
@sofushn

**Comment by sofushn** [comment]
> This issue is closed right? This is the commit that should have closed this issue right? 

yup
