### ISSUE TITLE
Make our product available on cit.ruc.dk

### ISSUE THREAD

**Issue by sofushn** [RUC-MSc-CS-CIT-2024/portfolio_subproject_1#61]

**Comment by idax6797** [comment]
Hi 

Ida Hay Jørgensen
Julius Krüger Madsen
Marek Laslo
Sofus Hilfling Nielsen

You are group cit11

You can use the following remote database for your group:
host: [cit.ruc.dk](http://rawdata.ruc.dk/)
port: 5432
database: cit11
user: cit11
password: PjoTrEdMzdoD

You can use the server while working on the Project Portfolio, but if you're accessing it from outside the University, you'll need a VPN connection and probably the local server on your own computer is faster. The only requirement for using the remote group database is that you must submit your database and the functions developed for Portfolio Subproject 1 by uploading everything into this database. If you make any changes to your database for Subprojects 2 or 3, ensure that these updates are also applied to the remote group database.

Best regards,
Troels
