### ISSUE TITLE
Script for populating data in the core model

### ISSUE THREAD

**Issue by sofushn** [RUC-MSc-CS-CIT-2024/portfolio_subproject_1#8]
Create scripts to move data from original data model into the new one based on the core model

All data should be part of the same script but can be made independently from each other and merged in the end when completing this task

## Subtasks

- [x] #9
- [x] #10
- [x] #11
- [x] #38

**Comment by JuliusKryger** [comment]
We agree the following issue/task can now be closed right?

> @idax6797 @MarLaslo @sofushn

**Comment by MarLaslo** [comment]
@sofushn added another checkbox field to complete
